name: Build gradle and/or publish (reusable workflow)

on:
  workflow_call:
    inputs:
      version:
        description: "release version"
        required: true
        type: string
      publish:
        description: "Specifies whether to publish the artifacts (defaults to false)"
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false
      - uses: actions/checkout@v4
      - name: Set version
        run: |
          sed -i "s/1.0.0-SNAPSHOT/${{ inputs.version }}/g" build.gradle.kts
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v3
      - name: Set gradle build publish arguments
        id: publish-arguments
        run: |
          if [ "${{ inputs.publish }}" == "true" ]; then
            echo "arguments=publish" >> $GITHUB_OUTPUT
          else
            echo "arguments=" >> $GITHUB_OUTPUT
          fi
      - name: Running gradle build
        uses: eskatos/gradle-command-action@v3
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        with:
          arguments: build ${{ steps.publish-arguments.outputs.arguments }} --no-daemon