name: Build on every push except main branch

on:
  push:
    branches-ignore:
      - main

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/build-gradle.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-build:
    uses: walt-id/waltid-identity/.github/workflows/build-docker.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}