name: Deploy to environment (reusable workflow)

on:
  workflow_call:
    inputs:
      version:
        description: "release version"
        required: true
        type: string
      deployment:
        description: "deployment file suffix (defaults to dev)"
        required: false
        type: string
        default: "dev"
      namespace:
        description: "deployment namespace (defaults to dev)"
        required: false
        type: string
        default: "dev"
      portals:
        description: "deployment namespace for portal related services (defaults to dev)"
        required: false
        type: string
        default: "dev"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.version }}
      PORTALS: ${{ inputs.portals }}
      NAMESPACE: ${{ inputs.namespace }}
      KEYCLOAK: ${{ secrets.DEV_KEYCLOAK_CLIENT_SECRET }}
    strategy:
      matrix:
        services: [
          { kube: waltid-services/waltid-issuer-api/k8s, name: issuer, namespace: $PORTALS },
          { kube: waltid-services/waltid-verifier-api/k8s, name: verifier, namespace: $PORTALS },
          { kube: waltid-services/waltid-wallet-api/k8s, name: web-wallet, namespace: $NAMESPACE, keycloak: $KEYCLOAK },
          { kube: waltid-applications/waltid-web-portal/k8s, name: portal, namespace: $PORTALS }
        ]
    steps:
      - name: Prepare CD - ${{ matrix.services.name }}
        run: |
          sed "s/_DEFAULT_DEPLOYMENT_/$GITHUB_SHA/g" ${{ matrix.services.kube }}/deployment-${{ inputs.deployment }}.yaml > ${{ matrix.services.kube }}/deployment_mod.yaml |
          sed "s/__DEFAULT_IMAGE_TAG__/$IMAGE_TAG/g" > ${{ matrix.services.kube }}/deployment_mod.yaml |
          if [ "${{ matrix.services.keycloak }}" != "" ]; then
            sed "s/__DEFAULT_KEYCLOAK_CLIENT_SECRET__/${{ matrix.services.keycloak }}/g" > ${{ matrix.services.kube }}/deployment_mod.yaml
          fi
      - name: Continuous deployment - ${{ matrix.services.name }}
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -n ${{ matrix.services.namespace }} -f ${{ matrix.services.kube }}/deployment_mod.yaml