name: Release on manual push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    with:
      preferred: ${{ inputs.release_version }}
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/build-gradle.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  docker-build:
    uses: walt-id/waltid-identity/.github/workflows/build-docker.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      tag: latest
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: [ version, gradle-build, docker-build ]
    with:
      version: ${{ needs.version.outputs.release_version }}
      deployment: prod
      namespace: default
      portals: portals
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  release:
    uses: walt-id/waltid-identity/.github/workflows/changelog.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: [ tag ]
    with:
      tag: ${{ needs.tag.outputs.tag }}