name: Deploy manually to test environment

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Custom version'
        required: false
jobs:
  version:
    uses: walt-id/waltid-identity/.github/workflows/version.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    with:
      preferred: ${{ inputs.release_version }}
  gradle-build:
    uses: walt-id/waltid-identity/.github/workflows/build-gradle.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
  docker-build:
    uses: walt-id/waltid-identity/.github/workflows/build-docker.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: version
    with:
      version: ${{ needs.version.outputs.release_version }}
      publish: true
  deploy:
    uses: walt-id/waltid-identity/.github/workflows/deployment.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    secrets: inherit
    needs: [ version, gradle-build, docker-build ]
    with:
      version: ${{ needs.version.outputs.release_version }}
  tag:
    uses: walt-id/waltid-identity/.github/workflows/tag.yml@3bf15fcc1152a2a8f97df759e39e3d755c3dc346
    needs: [ version, deploy ]
    with:
      version: ${{ needs.version.outputs.release_version }}